antenna/app.py
antenna/configlib.py
tests/test_app.py
tests/test_configlib.py

This tweaks configuration a little bit to make it easier to work with in the breakpad code I'm writing.
The only new feature is the `parse_class` parser. That should be pretty straight-forward.
The rest of it is nixing the config singleton for one that's instantiated when the app is created.

Modify config

---

Dockerfile
bin/ci/deploy-dockerhub.sh
circle.yml

update dockerfile to be based on python:2.7.12-slim, add circle.yml and boilerplate for building containers in circle
@willkg r+?
You can pull from dockerhub with `docker pull mozilla/antenna:unstable`. Once this is merged you can just `docker pull mozilla/antenna` and it will pull latest, which is built off of master.
:unstable will be built off of the latest non-master, non-tagged build (on any branch of _this_ repo)

Dockerfile updated to be based on python, circle building properly

---

.gitignore
Dockerfile
Makefile
docker-compose.yml

This fixes the Dockerfile to bind to 0.0.0.0:8000 because that makes
things work. This updates the Makefile and docker-compose.yml so we
can launch Antenna for development purposes.

Fix docker infrastructure

---

antenna/app.py
tests/conftest.py
tests/test_app.py

This implements one of the endpoints that Ops wants in order to run
Antenna in production.
This also removes the previous iteration of the HealthCheckResource.

Implement the /__version__ endpoint

---

antenna/app.py
antenna/external/crashstorage_base.py
antenna/external/fs/__init__.py
antenna/external/fs/crashstorage.py
antenna/util.py
docs/spec_v1.rst
tests/test_crashstorage.py

This implements a rudimentary file system crash store that mimics the
"directory structure" of what we're going to do on S3, but does it on
a local file system.
There are a bunch of FIXMEs that should get thought through at some
point, but since I'm only using this crash store for
development/testing purposes, I'm going to leave those be for now.

Implement FSCrashStore

---

antenna/external/crashstorage_base.py

Previously, if we got a raw_crash that was big with lots of keys, this
would log crazy unhelpful amounts of information. Now it logs
something more helpful.

Fix NoOpCrashStore logging

---

tests/unittest/conftest.py
tests/unittest/test_app.py
tests/unittest/test_fs_crashstorage.py

This fixes some issues with the test Client where the client has a copy
of the app, but we need to rebuild the app with a certain configuration
for some tests and it was awkward to get the right order of operations.
Now you can just call .rebuild_app() and give it a new configuration
and you're all set.

Cleanup test Client

---

Makefile

This tweaks the Makefile to allow for alternate docker-compose.yml
files by specifying a DCFILE environment variable. This makes things a
bit more flexible for testing different configurations.

Tweak Makefile to allow for alternate docker-compose.yml files

---

antenna/external/crashstorage_base.py
antenna/external/fs/crashstorage.py
tests/unittest/test_fs_crashstorage.py

This will make it easier to freeze and thaw crashes from the various
crash storage systems. That makes it easier to use antenna as a
library to build utilities for testing and scripts.

Add load_raw_crash

---

Dockerfile
Dockerfile.dev
Makefile
docker-compose.yml

This creates a bunch of docker stuff so that we can have a separate
docker image for doing development-specific things without having some
of the tools we need to install available in the deploy image.
The new local/antenna_dev image has make which we need to build the
docs.

Fix docs creation

---

Makefile
antenna/app.py

Previously, unhandled errors would propagate all the way up and Falcon
would just return an HTTP 500 to the client, but wouldn't log anything
which ... is unhelpful.
This replaces that with a handler that logs the exception and then
returns a HTTP 500 to the client.

Fix error handling

---

requirements.txt

Everett 0.3.1 fixes alternate_keys for components.

Upgrade to everett 0.3.1

---

antenna/app.py
tests/unittest/conftest.py
tests/unittest/test_crashstorage.py
tests/unittest/test_fs_crashstorage.py

Prior to this change, we were saving the crash during the HTTP
request/response cycle.
This fixes it so that we spawn an eventlet to handle storing the crash
and whatever else needs to happen so that we can return a crash id to
the breakpad client and end the HTTP conversation as soon as possible.
We put all the eventlets in a pipeline_pool so that we can count them
and keep track of them.
This also moves some yucky code out of the tests and into the test
client to improve the readability of our test code.

Move post handling to the eventpool

---

antenna/app.py
tests/unittest/conftest.py

Falcon has a global variable that it flips to False if it encounters a
request stream that it doesn't need to wrap. We have a test that
causes that to happen. So any test that runs before that test has run
and flipped the global to False fails.
For some reason that I didn't track down, the
falcon.request_helper.Body class doesn't work with cgi.FieldStorage
causing us to get empty crash reports and fail tests.
Instead of dealing with that, this explicitly flips the global to
False and adds a big comment about the situation. The thinking being
that this is our test suite, we don't need to test their wrapping and
we're running under gunicorn which doesn't trigger the wrapping.

Fix problems when running a single test

---

antenna/app.py
tests/unittest/conftest.py
tests/unittest/test_crashstorage.py

Prior to this, falcon.API would register routes, but it was tricky to
get a list of resources. In Antenna, resources are also components, so
we want to have a list of the ones in the app so that we can more
easily perform work across all the components in the app.
For example, it's hard to do a health check if you can't access all
the components in the app to ask them about their health.
This fixes that.

Implement AntennaAPI to manage resources

---

antenna/app.py
bin/create_fakes3_bucket.py

If ANTENNA_ENV wasn't defined, then Antenna would raise an exception
on startup due to a bug in Everett.
This changes the code so it doesn't tickle the bug.

Fix NoneType issues

---

antenna/external/s3/connection.py

boto3 can figure out credentials via a variety of different methods.
We're planning to bind an IAM role to an EC2 instance, so we don't
need credentials at all.
This fixes the code so that it doesn't require ACCESS_KEY and
SECRET_ACCESS_KEY and adds a note in the docstring about it.
This doesn't add a test for that scenario. It's trickt to add a test
without reaching deep into the bowels of boto3 and mocking stuff out at
which point I'm not sure what we're actually testing. So... that's
stinky, but so it goes.

Support other s3 credentials options

---

antenna/app.py
antenna/loggingmock.py
prod.env
tests/unittest/conftest.py
tests/unittest/test_s3_crashstorage.py

This adds a configurable logging level to setup_logging and the app
configuration.
This also fixes the logging mock and py.test fixture to work better
especially in regards to how setup_logging() only happens once.

Fix logging and logging mock

---

antenna/app.py
antenna/throttler.py
tests/unittest/conftest.py
tests/unittest/test_crashstorage.py
tests/unittest/test_fs_crashstorage.py
tests/unittest/test_throttler.py

This adds a throttler that behaves much like the throttler in the
current Socorro. There are some minor differences.
First, this throttler defines rule sets in Python. That makes things a
lot easier.
Second, this throttler merges DISCARD and IGNORE because in both cases
we're dropping the crash. Merging them simplifies the code a bit.
Third, this throttler names the rules. This will make logging better
plus it enables us to statsd our rules so we have some metrics about why
things tend to get accepted.
Fourth, other than configurable rule sets, the throttler is not
configurable. If you don't want throttling, use the "accept_all" rule
set.

Add a throttler

---

antenna/app.py

When running in a worker process with gunicorn, it's possible the code
dies and then gunicorn shuts down, but nothing gets printed to the
console so you have no idea what happened.
This wraps .get_app() so it prints something to the console on
unhandled exceptions.

Add logging of exceptions

---

antenna/app.py
antenna/health_resource.py
docs/configuration.rst
tests/unittest/test_health_resource.py

This adds a /__broken__ endpoint which we can use to trigger exceptions
which Sentry will catch which lets us test Sentry is working.

Bug 1316431: Add /__broken__ endpoint

---

antenna/ext/s3/crashstorage.py
tests/unittest/test_s3_crashstorage.py

This removes the extra / for s3 paths so they don't end up in a
//v2/raw_crash/... kind of pseudo-filename.

Bug 1323462: Remove extra / for s3 paths

---

antenna/breakpad_resource.py
tests/systemtest/test_content_length.py
tests/systemtest/test_discards.py

This cleans up the content-length handling code and the tests--the
test_no_content_length test was accidentally sending a content length.
This adds a test for when the content-length is more than the size of
the payload. This requires testing against nginx which will timeout the
connection after a minute (the right thing to do).

Fix content-length tests

---

antenna/breakpad_resource.py
tests/systemtest/test_content_length.py

If the payload isn't compressed or zlib throws an error when
uncompressing the payload, we should treat it as junk and move on.

Bug 1322077: Fix zlib issue

---

tests/systemtest/test_content_length.py

If the POSTURL is an https url, then the content-length tests would fail because
we were always using HTTPConnection. This fixes that.
@milescrabill Pretty sure this fixes it, but I can't test it locally, so ... meh. Does it look ok?

Fix content-length systemtests to correctly use https

---

tests/systemtest/conftest.py
tests/systemtest/test_content_length.py
tests/systemtest/test_post_crash.py

* the content-length test should be checking for a 504--not a 200
* the post-crash tests were verifying using pseudo-filenames that ended up with
// in them which I'm pretty sure caused them to fail
* added some more debug logging so failures are easier to debug
@milescrabill Does this look ok?

Fix content-length test and post-crash tests

---

antenna/breakpad_resource.py
antenna/ext/crashstorage_base.py
antenna/ext/fs/crashstorage.py
antenna/ext/s3/crashstorage.py
tests/unittest/test_crashstorage.py

This splits save_raw_crash into save_raw_crash and save_dumps. The reason for
this is so that we can save the raw crash independently of the dumps if we need
to and thus reduce S3 work.

Bug 1329998: Split save_raw_crash up

---

antenna/breakpad_resource.py
tests/unittest/test_breakpad_resource.py
tests/unittest/test_crashstorage.py
tests/unittest/test_fs_crashstorage.py

This fixes a couple of minor differences in raw_crash files between the current
Socorro collector and Antenna. For some reason, when writing Antenna, I renamed
"throttle_rate" to "percentage". Probably to line up with the new Rule system
architecture I had. Who knows. Anyhow, fixed.

Bug 1325388: Fix parity problems

---

antenna/breakpad_resource.py
antenna/metrics.py

We want histogram stats for crash sizes since we want to know median, 95% and
max. Gauge is the wrong thing for that. This fixes it.

Bug 1336533: Switch gauge to histogram

---

Dockerfile

1001 corresponds to a Puppet-added user. We should change that.
@willkg r?

Change user/group ID to prevent overlap

---

antenna/breakpad_resource.py

This adds a metric that tells us the total time it took between getting the HTTP
POST request to saving all the bits to s3. We do it as a timing so we can get
median, 95% and max rates in Datadog.

Bug 1337859: Capture end-to-end timing

---

antenna/ext/s3/connection.py

Fixes a bug where the wrong argument type was being passed into .add_error().

Bug 1339403: Fix TypeError

---

antenna/breakpad_resource.py
tests/unittest/test_breakpad_resource.py
tests/unittest/test_health_resource.py

Previously, uploading crash data to s3 would happen concurrently and Antenna
would spin off a new coroutine for every crash it was handling. That doesn't
scale.
This changes it so that there's an explicit queue and we cap the number of
actively saving-to-s3 coroutines at CONCURRENT_SAVES.

Bug 1342525: Fix queuing of s3 uploads

---

antenna/ext/s3/connection.py
antenna/util.py
tests/unittest/test_s3_crashstorage.py
tests/unittest/test_util.py

This reworks the retry code so it's easier to work with. It also changes boto3
client creation so that it gets retried a few times if it fails.
The theory here is that in Antenna -stage, the boto3 lib does an HTTP request to
get the credentials, gets rate-limited and then fails and that hoses Antenna's
ability to start up. Assuming the theory is right, this will alleviate that a
bit.

Bug 1342619: Make boto3 client creation retryable

---

antenna/breakpad_resource.py

This lets us compare number of crashes accepted (which happens whe the crash is
taken in by the WSGI handler) vs. number of crashes saved to s3. If these two
numbers get very far apart, then it's an indicator that things are not good.

Add crash save metric

---

antenna/breakpad_resource.py
tests/unittest/conftest.py
tests/unittest/test_breakpad_resource.py
tests/unittest/test_health_resource.py

Previously, Antenna would emit health stats for the save queue size and active
worker pool size as statsd data when /__heartbeat__ was handled. However, that
only gets handled by one process on the node, so the data we're getting back
from a node isn't the whole story and we won't get back data from orphaned
processes that aren't handling HTTP requests.
This changes the architecture so that BreakpadResource has a heartbeat coroutine
that sleeps 30 seconds and then emits stats.

Bug 1342606: Move health stats to a heartbeat

---

antenna/breakpad_resource.py
tests/unittest/test_breakpad_resource.py

This renames some things to "crashmover" and related names. This should make it
easier to understand in the context of the current Socorro collector that this
replaces.
This changes the number of concurrent crashmovers running. Previously, we had 10
running. But it was actually (10 * number-of-processes) which is 50 per node and
they were all fighting for upload bandwidth. This changes that to 1 so there are
at most 5 per node. That should work a *lot* better.

Redo crashmoving

---

antenna/metrics.py

We're having possibly problems with datadog and metrics. This tosses the batched
counter metrics to the logs so we have a way to double-check.

Log batched stats

---

antenna/ext/s3/connection.py
antenna/heartbeat.py
antenna/metrics.py
antenna/sentry.py

This changes the code to retry ValueError when trying to build a client. We get
a ValueError when boto3 uses the wrong endpoint.
Our theory is that it tries to get credentials and fails for some reason, then
degrades to this endpoint and fails.
Now if it hits this scenario (which seems to happen a lot when we start a new
node), it'll retry 5 times over 10 seconds (might not be enough--we'll find
out).
This also logs a line if it sent something to Sentry.

Bug 1347185: fix s3 connection problems

---

antenna/sentry.py

This logs something if the Sentry client isn't set up and that's why it's not
sending unhandled exceptions to Sentry.

Adjust capture_unhandled_exceptions

---

antenna/app.py
antenna/util.py
tests/unittest/test_util.py

Right now we're getting insane interleaved logs which makes extracting
tracebacks impossible. This improves that by changing it so it logs the whole
thing as one line.

Log exceptions as one line

---

antenna/app.py
tests/unittest/conftest.py

This makes it possible to set the host id in the logs to whatever you want using
the HOST_ID environment variable. This makes it easier to set the host id to
something that you can later use to correlate items in logs to other data
systems.

Bug 1349995: Allow changing host id in logs

---

antenna/app.py
antenna/health_resource.py
antenna/sentry.py
antenna/util.py

This adjusts the Sentry client creation so that it sends the commit sha of the
deployed code as a tag with all Sentry reports.
The reason we do this instead of sending the release is that this doesn't
require us to create the release every time we do a deploy.

Send commit as tag to Sentry

---

antenna/health_resource.py
antenna/util.py
tests/unittest/test_util.py

`get_version_info` was returning a string--not a dict. The Sentry code was expecting a dict.
This fixes `get_version_info` to return a dict and fixes the `/__version__` endpoint to work with that correctly and adds a test.

Version info fix

---

antenna/ext/s3/connection.py

This fixes the root: vars for the S3 Connection and the documentation so it
aligns better with boto3's credentials usage. Why do this? It reduces some
unneeded complexity.

Fix S3 Connection to align better with boto3 creds usage

---

antenna/app.py
antenna/breakpad_resource.py
antenna/health_resource.py
antenna/throttler.py
docs/architecture.rst

This reduces a lot of extra stuff in the metrics keys making them shorter and
easier to write out.

Bug 1354897: Clean up metrics keys

---

antenna/breakpad_resource.py
antenna/metrics.py
tests/unittest/test_metrics.py

We were having problems where graphs weren't lining up. I did some work and
theorized that since Antenna sends the same value a lot, that some of them were
getting dropped during the "normalize for a flush interval" period. Thus I
implemented batching of counters that occur often.
Since then, I've learned a lot more about statsd and I think all those theories
are rubbish.
Given that the theories are rubbish and while in the bug comments I claim that
batching helped, I don't think it actually did help at all and I think I was
interpreting the data noise incorrectly.
This commit removes the batching code because it's probably not actually helping
at all and thus it's adding unneeded code complexity.

Bug 1343708: Remove batch_incr

---

antenna/breakpad_resource.py

If the payload is empty, just drop it--no need to do any more work on it.

Fix on_post to short-circuit empty payloads

---

antenna/throttler.py
tests/unittest/test_throttler.py

For crashes that don't match any of the throttler rules, we should defer
them--not reject them. This fixes that.

Fix throttler

---

antenna/breakpad_resource.py
antenna/ext/s3/connection.py
tests/unittest/test_breakpad_resource.py

* change crash saving retrying so that it only retries 20 times and then gives
up; each time it sends something to sentry so we shouldn't miss it.
* add a test for the new retry behavior

Bug 1356671: Fix crash saving exception handling

---

antenna/breakpad_resource.py

I can't for the life of me figure out how a None can end up as a key in the
raw_crash. Everything I do to try to coerce extract_payload() into yielding a
None is for naught. Thus this is a blind fix for something I can't reproduce.

Bug 1356671: Blind fix for None keys in raw_crash

---

Dockerfile.motos3
Makefile
README.rst
antenna/ext/s3/connection.py
bin/create_s3_bucket.py
dev.env
docker-compose.yml
tests/systemtest/README.rst

This switches from fake s3 to moto. This solves several problems the biggest of
which being that they no longer distribute fakes3 under and Open Source license.
The other problem this solves is that fakes3 doesn't let you list buckets which
we now need.
This uses a specific commit in the master branch after release 0.4.31 because
that release has bugs that prevent us from creating buckets.

Bug 1351914: Switch to moto for fake s3

---

antenna/breakpad_resource.py
tests/unittest/test_breakpad_resource.py
tests/unittest/test_util.py

This adds de-nulling to keys and filenames in addition to values which Antenna
already did.

Bug 1357452: Fix extract_payload to de-null keys and filenames

---

antenna/breakpad_resource.py
antenna/throttler.py

This moves the incr for the throttle rule into the breakpad_resource to a place
where we have the rule used even if we picked a rule without running through the
throttler.
This will additionally cover NO_MATCH, THROTTLEABLE_0, ALREADY_THROTTLED, and
FROM_CRASHID.

Bug 1357944: Move incr for throttle rule

---

antenna/app.py
antenna/breakpad_resource.py
antenna/health_resource.py
antenna/sentry.py
tests/unittest/test_app.py
tests/unittest/test_breakpad_resource.py

This changes content-types for responses to application/json where possible. It
clarifies why we have text/plain for the breakpad resource. It removes the
homepage resource so that returns a normal 404 now.

Clean up content-types in responses

---

antenna/app.py

When defined on the logger, it doesn't trigger at all. When defined on the
handler, it works super.

Fix the AddHostId filter configuration

---

requirements.txt
tests/systemtest/run_tests.sh

Python 3.3+ has virtualenv built-in. This drops the library for the built-in one.

Ditch virtualenv requirements

---

antenna/breakpad_resource.py
tests/unittest/test_breakpad_resource.py

This fixes the throttle character checking code to no longer assume it's an
int-like thing.
Further, it reworks all the tests for getting the throttle result and cleans
them up significantly.

Bug 1365416: Fix throttle character checking

---

antenna/throttler.py
tests/unittest/test_throttler.py

This makes sure there's a non-empty ProductName before checking the first
character.

Bug 1381713: fix indexerror in is_thunderbird_seamonkey rule

---

Makefile
bin/build_docs.sh

This redoes "make docs" so that the resulting files have the permissions of the
host user which makes life soooooo much easier.

Rework docs scripts to build with right permissions

---

antenna/throttler.py
tests/unittest/test_throttler.py

We've produced release candidates for QA with a browser configuration fix for all channels. This adjusts the build id to match to the date. ESR is built with a PST timestamp while the others are build with UTC, so we cannot get more specific than that. 
🎉 🎉 🎉

updates buildid with new release candidates

---

docs/breakpad_reporting.rst

This updates the tips on how to trigger a crash (and a crash report) in
Firefox.

Update docs on triggering a crash in Firefox

---

antenna/breakpad_resource.py
tests/unittest/test_breakpad_resource.py
tests/unittest/test_crashstorage.py
tests/unittest/test_fs_crashstorage.py

This switches `dump_checksum` from md5 hexdigest to sha256 hexdigest. We don't use this currently, but sha256 is better and maybe we'll use it for something someday.
This adds a new MinidumpSha256 field with the sha256 hexdigest of the `upload_file_minidump` file.
This also moves the checksum-figuring code out of `extract_payload` and into the `on_post` handler near other code that adds fields to the raw crash.

fix bug 1409427 - switch to sha256 and add MinidumpSha256 checksum

---

antenna/throttler.py
tests/unittest/test_breakpad_resource.py
tests/unittest/test_crashstorage.py
tests/unittest/test_fs_crashstorage.py
tests/unittest/test_throttler.py

This switches the throttler to reject unsupported products. We'll add
products to this list over time as requested.
This also cleans up the throttler. It gets rid of the weirdness around
conditions, so now all conditions are functions. It gets rid of the
one regexp--we could do the same thing without a regexp. It adds
documentation.

fix bug 1476941: reject unsupported products

---

docs/requirements.txt

ReadTheDocs can only handle one requirements file (as far as I can see), so
this creates one that points at the two files we have in this repo.

Add docs requirements files

---

antenna/breakpad_resource.py
antenna/throttler.py
tests/unittest/test_breakpad_resource.py
tests/unittest/test_throttler.py

This changes the throttle default from `DEFER` to `REJECT`. So instead of
Socorro saving everything even if it's not going to process it, it will
now only save crash data for crash reports it plans to process.

fix bug 1480936: change throttle default to REJECT

---

antenna/throttler.py
tests/unittest/test_throttler.py

We had a rule for throttling pre-57 at 20% rather than the normal 10%.
This helped us catch up with our data after deleting everything.
We no longer need this, so it's time to remove it. This commit does that.

fix bug 1440031: remove pre-57 throttle rule

---

antenna/breakpad_resource.py
antenna/throttler.py
tests/unittest/test_throttler.py

B2G products send crash reports and will retry ad infinitum on any non-accept.
This fixes the throttler to handle this explicitly by "fake accepting" the
crash. This involves sending an accept-like response, but throwing the crash
away.
We want to be super careful doing this because we're throwing crash data away.
It's ok in this case because we don't want B2G crash data and we don't want
B2G devices to be trying to resend over and over again.

fix bug 1500243: add fakeaccept for b2g

---

antenna/app.py
dev.env
tests/unittest/conftest.py

This fixes logging so it uses mozlog in a server environment and console
in a local dev environment. This makes logs muuuuuch easier to read
when working on things.

fix bug 1527919: use console logging in a local dev environment

---

requirements/default.txt
testlib/s3mock.py
tests/unittest/conftest.py
tests/unittest/test_s3_crashstorage.py

The s3 test class names were weird and there were two classes but only need to be one. This fixes both of those issues.
Antenna isn't using pytest-env, so best to remove it.
This doesn't redo the s3mock stuff altogether, but does fix some minor things with it.

bug 1517807: Fix s3 test class name; remove pytest-env

---

antenna/ext/pubsub/crashpublish.py
antenna/ext/s3/connection.py
antenna/ext/s3/crashstorage.py
bin/create_s3_bucket.py
tests/unittest/test_s3_crashstorage.py

This fixes the `S3CrashStorage` startup check to verify that it can write to the S3 bucket instead of just HEADing the bucket which is a different permission.
This also adds a `PubSubCrashPublish` health check which verifies it can access the topic.

fix bug 1359147: fix s3 and pubsub startup and health checks

---

antenna/breakpad_resource.py
testlib/mini_poster.py
tests/unittest/test_breakpad_resource.py

This adds support for encoding the raw crash extra bits as a single
JSON-encoded value rather than as a series of key-value pairs in
the multipart/form-data serialized HTTP payload.

fix bug 1533732: add support for JSON-encoded fields

---

docker/Dockerfile

Gunicorn can preload the entire application before spinning off workers
which saves time and memory. However, it calls gevent monkeypatch after
spinning off the workers, so a bunch of stuff has imported things that
need to be monkeypatched before monkeypatching. I'm pretty sure this
is what's causing the sporadic SystemExits we're seeing.
This shuts off preload.

bug 1538202: remove preload

---

antenna/ext/pubsub/crashpublish.py
antenna/gunicornhooks.py
tests/unittest/conftest.py

This adds a couple of `monkey.patch_all()` calls to guarantee gevent patching
before importing/usage of those things. This should fix issues in the pubsub
code. It also quells a warning when running pytest.

bug 1538202: add monkey.patch_all() calls to guarantee patching

---

docker/Dockerfile

This fixes the CMD so that it's using the worker class that initializes
grpc for gevent.
Previously this was configurable, but since we require this class in order to
make gevent and grpc, I changed it so that it's no longer configurable.

bug 1538202: fix the docker CMD line to use the new worker

---

antenna/throttler.py
tests/unittest/test_throttler.py

The thinking is that we don't get many of these crash reports so we should
process all the ones we do get. I'm estimating this increase processed
crashes per week by about 10,000 which should be fine.

bug 1547804: process all ProcessType=gpu crash reports

---

antenna/breakpad_resource.py
tests/unittest/test_breakpad_resource.py

This changes the breakpad crash report handling code to return something
like "Discarded=somereason" instead of "Discarded=1". Reasons are
alphanumeric one-word values that indicate what the problem was.
While doing that, I tweaked how extract_payload works for error
situations--now it throws a MalformedCrashReport exception.

bug 1557706: specify why crash report was discarded

---

.pyup.yml

In a previous PR, I removed `.pyup.yml` altogether. I think that didn't shut off pyup but rather caused pyup to use the defaults. Then it added a bazillion PRs.
I was thinking about this. Having Antenna not have automated dependency updates was ok when I was maintaining it because I could do a 6-month update manually and that was fine. Making Antenna maintainable by not-me is important. I think switching to a monthly update cycle that's automated is better than no automated update cycle for not-me maintenance.
Thus, this switches it to the same configuration Socorro has.

bug 1559151: add pyup and set to monthly updates

---

antenna/breakpad_resource.py

We've got this problem where crash payloads with a JSON serialized extra field
are getting rejected by Antenna for unclear reasons. It seems like there are
extra fields involved, but we can't figure out where they're coming from or
what they look like.
This adds some logging that I can check later that'll help suss out the
problem.

bug 1560168: add logging for json-and-kv situation

---

bin/release.py

This adds a `release.py` script for creating a deploy bug and tagging the
repository for deploy. This automates some of the work we've been doing
by hand.
This also codifies the tag scheme change to `YYYY.MM.DD`.

bug 1561628: add bin/release.py script

---

requirements/default.txt

This replaces pr #350 .
This doesn't update boto3 and friends because that breaks the s3 mock. Bug 1517807 covers that.
This doesn't update falcon because the jump to 2.0 involves some non-trivial reworking of things.

Update pytest and bandit to current versions

---

README.rst
bin/sqs_cli.py
docker-compose.yml
docker/config/local_dev.env
docker/run_tests.sh
docker/run_tests_in_docker.sh
requirements/default.txt
tests/unittest/test_bin.py

This:
1. updates localstack to 0.10.5
2. updates boto3 and botocore to their latest versions
3. adds the scaffolding for running an SQS emulator in the local dev environment,
4. adds some configuration for it that doesn't interfere with existing things,
5. adds a cli tool for manipulating SQS state
Of these, the only thing that affects server environments is the boto3/botocore version updates. I didn't see anything specific that would affect Antenna, though, so I think this is just a version bump.

bug 1598765: local sqs

---

antenna/ext/s3/connection.py
antenna/ext/sqs/__init__.py
antenna/ext/sqs/crashpublish.py
bin/sqs_cli.py
docker/config/local_dev.env
docker/run_setup.sh
docs/configuration.rst
tests/unittest/conftest.py
tests/unittest/test_pubsub_crashpublish.py
tests/unittest/test_sqs_crashpublish.py

This implements an `SQSCrashPublish` class which publishes crash ids to an AWS SQS standard queue. It includes configuration, tests, and documentation for setting it up.
It is not enabled by default--the default crash publisher is still `NoOpCrashPublish`.
This won't affect production or the local dev environment. This adds the collector bits so that we can then add the processor/webapp bits.

bug 1601455: add AWS SQS crashpublish support

---

docker/run_setup.sh

`docker/run_setup.sh` requires services to be started. If the machine is fast enough, they may not be running by the time `docker/run_setup.sh` is called which causes it to fail. This reduces that by adding urlwait calls.

Add urlwait calls to docker/run_setup.sh

---

antenna/breakpad_resource.py
tests/unittest/test_breakpad_resource.py
tests/unittest/test_fs_crashstorage.py

This adds a note to the raw crash that tells us how the annotations were encoded in the crash report. Were they in a JSON-encoded value in the "extra" field? Were they encoded as key/value pairs in the
multipart/form-data?

bug 1608104: add note about annotations in crash report

---

antenna/breakpad_resource.py

This adds "malformed_" as a prefix to the Discarded reason so as to make it possible to distinguish between rejections because the crash report is malformed and rejections because of a rule.
This also changes malformed crash report HTTP responses to have a 400 status code.
To test:
1. run antenna
2. post a bad request:
```
$ curl --verbose -X POST http://localhost:8000/submit
*   Trying 127.0.0.1:8000...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8000 (#0)
> POST /submit HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.65.3
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< Server: gunicorn/20.0.4
< Date: Wed, 15 Jan 2020 16:39:42 GMT
< Connection: keep-alive
< content-type: text/plain
< content-length: 35
< 
* Connection #0 to host …
```

bug 1609440: distinguish between rejections

---

antenna/throttler.py
tests/unittest/test_throttler.py

This adds two throttling rules. One rejects incoming Thunderbird crash reports for major version > 68. The other rejects incoming SeaMonkey crash reports > 2.49.5.
This adds notes to remove these rules and remove Thunderbird and SeaMonkey from the supported products in January 2021. It's possible the timeline may change between now and then. If that happens, someone will update the notes.

bug 1604848: reject incoming thunderbird > 68 and seamonkey > 2.49.5

---

antenna/breakpad_resource.py
tests/unittest/test_breakpad_resource.py
tests/unittest/test_fs_crashstorage.py

This adds code for removing fields that should never exist in crash reports before the crash reports are saved anywhere.
Currently, this removes `TelemetryClientId` and `TelemetryServerURL`. These are stripped from the crash report before being sent, but in case they aren't, this removes them in the collector.
@jwhitlock wondered why we don't have a schema for what gets accepted and reject anything that's not in the schema. That wasn't doable before, but might be doable now. It's a pretty big change from how we do things currently. It might mean we need a schema per product. It's something we should think about at some point in 2020 or 2021.

bug 1610540: add code for removing fields

---

antenna/breakpad_resource.py
tests/unittest/test_breakpad_resource.py

If the JSON value kicks up a `JSONDecodeError`, then there's something wrong with the JSON and Antenna should reject the crash report with an error.

bug 1614985: handle JSONDecodeError in json value

---

antenna/throttler.py
tests/unittest/test_throttler.py

SeaMonkey 2.53.1 released over the weekend and the collector should accept crash reports from it for now. This updates the filter accordingly.

bug 1619101: update seamonkey filter to 2.53.1

---

docker/Dockerfile

This was using the old gunicorn worker class that we created to handle making grpcio aware we were using gevent. Now that we're not using Pub/Sub, we aren't using grpcio and thus we don't need that anymore and can go back to the gevent worker.
The infrastructure sets the `GUNICORN_WORKER_CLASS` variable, so we should use that.

bug 1618201: fix gunicorn worker class to be configurable

---

antenna/throttler.py
tests/unittest/test_throttler.py

It's now possible for the collector to get `None` values for crash annotations. `None` is not a string which makes some of the throttler rules sad.
This adds a `safe_get` function which gets the value from the crash and forces it to be a string. Then we can use string functions on it.

bug 1619644: handle None values in throttler

---

antenna/throttler.py
tests/unittest/test_throttler.py

These are not really *crashes* and we get an awful lot of them. This reduces the number we're getting by 90%.
This adds a new throttle result: `CONTINUE`. When `CONTINUE` is returned, the throttler should continue through the rules--it's not an end state.

bug 1624949: throttle ShutDownKill crash reports

---

antenna/breakpad_resource.py
tests/unittest/test_breakpad_resource.py

If the parsed boundary is not a `str`, then `cgi.FieldStorage` throws a
`ValueError`. This catches that and throws a `MalformedCrashReport`.

bug 1381712: wrap fieldstorage call in try/except for bad boundaries

---

antenna/breakpad_resource.py

If the JSON-encoded value has a bad character in it, it'll kick up a `UnicodeDecodeError`. This adds handling for that situation.

bug 1619640: fix UnicodeDecodeError when decoding JSON

---

Makefile

The service containers can be up, but the services might not be running,
yet. This reduces the likelihood that the tests lose the race.

bug 1668583: reduce race between services and tests running

---

.circleci/config.yml
Makefile

This explicitly sets the Docker version. If we don't set the version,
CircleCI defaults to using 17.03.0 which is a version that CircleCI is
deprecating.

Update docker version in CircleCI config

---

docker/Dockerfile
requirements.in
requirements.txt

* Bump pytest from 6.1.0 to 6.1.2 (from PR #649)
* Bump everett from 1.0.2 to 1.0.3 (from PR #648)
* Bump flake8 from 3.8.3 to 3.8.4 (from PR #647)
* Bump botocore from 1.18.10 to 1.18.18 (from PR #646)
* Bump dockerflow from 2020.6.0 to 2020.10.0 (from PR #645)
* Bump python from 3.8.6-slim to 3.9.0-slim in /docker (from PR #644)

dependency updates 20201102

---

.circleci/config.yml

This adds dockerhub auth so as to reduce rate-limiting. When PRs are
based on a branch from a fork, they won't auth, but they should continue
to work.
This changes the environment variables used to conform to dockerflow
conventions. This also picks up using DOCKERHUB_REPO.

bug 1669245: add dockerhub auth and conform to dockerflow

---

antenna/breakpad_resource.py
tests/unittest/test_breakpad_resource.py
tests/unittest/test_fs_crashstorage.py

This annotation captures whether the incoming payload was compressed or
not at ingestion.

bug 1680046: add payload_compressed annotation

---

requirements.in
requirements.txt

* Bump sphinx from 3.2.1 to 3.3.1 (from PR #655)
* Bump more-itertools from 8.5.0 to 8.6.0 (from PR #654)
* Bump pip-tools from 5.3.1 to 5.4.0 (from PR #653)
* Bump requests from 2.24.0 to 2.25.0 (from PR #652)

Updates 20201201

---

antenna/breakpad_resource.py
antenna/util.py
tests/unittest/test_breakpad_resource.py
tests/unittest/test_fs_crashstorage.py
tests/unittest/test_util.py

Antenna adds a bunch of fields to the raw crash to help us understand what happened at ingestion. This removes the following:
* type_tag -- we don't use this
* legacy_processing -- this isn't helpful since we don't need to distinguish between ACCEPT and DEFER anymore
* throttle_rate -- this isn't interesting to know after the fact
* timestamp -- we can use submitted_timestamp to calculate how long it took to collect the crash

bug #1687987: remove unhelpful added fields from raw crash

---

antenna/breakpad_resource.py
antenna/throttler.py
tests/unittest/test_throttler.py

This adds `Email` to the list of fields that we drop at ingestion so it doesn't get saved in our system.

bug 1688905: add Email to list of fields we drop at ingestion

---

antenna/throttler.py
tests/unittest/test_s3_crashstorage.py
tests/unittest/test_sqs_crashpublish.py

This changes Antenna to reject incoming crash reports for Fennec.

bug 1699236: end support for Fennec

---

.readthedocs.yml

ReadTheDocs doesn't support Python 3.9, so set it back to 3.8.

Fix ReadTheDocs configuration to use Python 3.8

---

requirements.in
requirements.txt

* Bump more-itertools from 8.7.0 to 8.8.0 (from PR #719)
* Bump sphinx from 3.5.4 to 4.0.2 (from PR #718)
* Bump click from 7.1.2 to 8.0.1 (from PR #717)

Updates 20210601 2

---

docker/Dockerfile

* Bump python from 3.9.5-slim to 3.9.6-slim in /docker

Bump python from 3.9.5-slim to 3.9.6-slim in /docker

---

antenna/app.py
antenna/libsentry.py

The sentry client was set to send all logged messages to Sentry. That's
not what we want--we only want errors. This fixes that.
While doing that, I renamed the module and fixed some variable names so
they fit our naming scheme better.

bug 1723964: fix sentry logging

---

systemtest/test_dockerflow.py

This fixes the version check in the dockerflow systemtest so it passes
with both a local dev environment (empty dict) and server environments
(dict with stuff in it).

Fix the version check

---

docker/Dockerfile
requirements.in
requirements.txt

pip-tools 6.5.0 fixes the issue it had with pip 22. This removes the restriction we put in place.

Update pip-tools to 6.5.0 and remove pip restriction

---

.circleci/config.yml
Makefile

This switches from mozilla/cidockerbases which is deprecated to
cimg/base which is not.

bug 1756223: change ci docker image

---

.circleci/config.yml
Makefile
bin/run_tests.sh

This undoes the "touch .docker-build" line. Docker image tags don't seem
to be available between jobs.
This also fixes the lint job to use the make rule so we're not
specifying it in two places.

bug 1756223: fix lint and test CI jobs

---

.circleci/config.yml
Makefile
docker-compose.yml

The version.json file isn't in the image that got pushed to dockerhub.
This reworks things so that the build job saves the image to the
workspace and that's used for subsequent jobs.

bug 1756223: fix version.json

---

.circleci/config.yml
Makefile
README.rst
antenna/util.py
bin/run_setup.sh
bin/run_tests.sh
docker-compose.yml
docker/config/local_dev.env

Updating to localstack 0.14.0 lets us simplify our local dev environment
a little. We only have to run a single localstack service which handles
both SQS and S3.
While doing this, I fixed an issue with retrieving version.json in the
local dev environment and I updated the README.

bug 1757039: update to localstack 0.14.0

---

antenna/breakpad_resource.py
tests/unittest/test_breakpad_resource.py

extra should be a JSON-encoded dict of key/value pairs. If it's not a
dict, then that's malformed and we should treat it as such.

bug 1748256: handle when extra is not a dict value

---

tests/unittest/conftest.py
tests/unittest/test_crashmover.py
tests/unittest/test_s3_crashstorage.py
tests/unittest/test_throttler.py

A while back, I redid how logging was set up in Antenna which removed
the need for caplogpp, but I never actually removed caplogpp. This
removes it.

bug 1669981: remove caplogpp

---

antenna/breakpad_resource.py
antenna/util.py
tests/unittest/test_breakpad_resource.py
tests/unittest/test_util.py

Python 3.11 is deprecating the cgi module which has the FieldStorage class that we were using for parsing multipart HTTP payloads. Falcon 3.0 added handling code for multipart payloads. This switches to using that.
When this deploys to stage, we're going to want to verify it's working and that all the annotations are there. We should spend some time comparing crash reports on stage with those on prod. They should be the same (modulo submitted_timestamp and a few other fields).

bug 1562641: rework payload handling

---

.circleci/config.yml

This fixes the jobs in the workflow to run on tags. CircleCI doesn't
run jobs on tags by default, so we have to explicitly tell it to.

bug 1757748: fix jobs in workflow to run on tags

---

requirements.in
requirements.txt

* Bump pytest from 6.2.5 to 7.0.1 (from PR #798)
* Bump sentry-sdk from 1.5.4 to 1.5.6 (from PR #797)
* Bump pip-tools from 6.5.0 to 6.5.1 (from PR #796)
* Bump bandit from 1.7.2 to 1.7.3 (from PR #795)
* Bump botocore from 1.23.47 to 1.23.54 (from PR #794)

Updates 20220302

---

antenna/breakpad_resource.py

This restricts payload extraction to treating only parts of type
text/plain as annotations. It also adds some debugging code to send
errors to sentry when we see parts that aren't test/plain or
application/octet-stream.
I think this will alleviate the bug but also make other situations more
obvious.

bug 1757786: restrict annotation handling and add debugging

---

antenna/breakpad_resource.py

The default max_body_part_buffer_size is 1mb which probably isn't large
enough for minidumps. This increases it to a semi-arbitrary 20mb.

bug 1757801: increase max_body_part_buffer_size

---

bin/run_lint.sh
systemtest/conftest.py
systemtest/test_post_crash.py

This moves some bits around in the systemtest code to make it easier to
use for debugging crash report submission bugs.

bug 1757854: make systemtests easier to use for debugging

---

.circleci/config.yml

The difference in sizes isn't very much, but the difference in the time
it takes to compress the image is 10-15s which is a chunk of build time.

bug 1756223: have gzip do a fast compression pass

---

antenna/breakpad_resource.py
bin/s3_cli.py
tests/unittest/test_breakpad_resource.py

This improves the s3_cli giving it the ability to download files.
This improves the error messages from extract_payload so it's easier to identify and fix crash reporter client errors.
Previously, we had:
* malformed_no_content_type
* malformed_wrong_content_type
* malformed_no_boundary
* malformed_no_content_length
* malformed_bad_gzip
* malformed_bad_json
* malformed_no_annotations
* malformed_has_json_and_kv
Now, we've got:
* malformed_no_content_type
* malformed_wrong_content_type
* malformed_no_boundary
* malformed_no_content_length
* malformed_bad_gzip
* malformed_invalid_json
* malformed_invalid_json_value
* malformed_invalid_annotation_value
* malformed_invalid_payload_structure
* malformed_no_annotations
* malformed_has_json_and_kv
That makes it easier to differentiate between …

bug 1760187: improve s3_cli and extract_payload error messages

---

.circleci/config.yml
docker/Dockerfile.fakesentry

This updates kent (fakesentry service) to 0.4.1 which fixes the problem
it has with Flask 2.1.0.

bug 1762055: update kent to 0.4.1

---

antenna/throttler.py

This adds Thunderbird to the list of supported products so the collector
accepts crash reports for it.

bug 1762182: add support for thunderbird

---

antenna/app.py
tests/unittest/test_sentry.py

This fixes the Sentry event to have a transaction name that makes it
easier to triage events in the Sentry interface.
This also pulls most of the Sentry configuration code into one place so
we can document how it needs to be configured.

bug 1764571: fix data in Sentry event

---

antenna/ext/s3/crashstorage.py
docs/overview.rst
docs/spec_v1.rst
systemtest/conftest.py
systemtest/test_content_length.py
systemtest/test_discards.py
testlib/mini_poster.py
tests/unittest/test_s3_crashstorage.py

This removes the entropy portion from the raw crash path so it goes from this:
```
v2/raw_crash/ENTROPY/DATE/CRASHID
```
to this:
```
v1/raw_crash/DATE/CRASHID
```
That matches the work done in Socorro.
I ran the tests, posted some crash reports, and verified the contents of the bucket are in the right directory structure.

bug 1604845: remove entropy from raw crash path

---

antenna/breakpad_resource.py
requirements.in
requirements.txt
tests/unittest/test_breakpad_resource.py
tests/unittest/test_fs_crashstorage.py

This switches to the version 2 of the raw crash structure wherein we move most of the collector-added fields into a `metadata` section and additionally add a `version` field denoting the raw crash structure version.
This also reworks `BreakpadSubmitterResource` so it's passing around a `CrashReport` and then generate the raw crash structure from that. That makes it a little easier to see the whole structure since it's in one place.
This also stop generating `MinidumpSha256Hash` fake annotation.
To test:
1. post a crash
2. use `s3_cli.py` to download the data and verify it's valid version 2 raw crash structure

bug 1687987: switch to raw crash version 2

---

antenna/breakpad_resource.py
tests/unittest/test_fs_crashstorage.py

This adds the throttle rule that caused the crash to be accepted to the raw crash metadata. This lets us debug things down the road.

bug 1763225: add throttle rule to raw crash metadata

---

.circleci/config.yml
Makefile
docker-compose.yml
docs/configuration.rst
docs/dev.rst

Previously, we supported docker-compose < v2. This changes it so that we require at least v2.

bug 1791209: support docker compose v2+

---

docker/Dockerfile

This switches to running the entrypoint with tini which listens for interrupts and shuts down processes correctly.
This also removes the apt cache bits in the Docker image build reducing the image size by around 40mb.

bug 1819200: use tini

---

requirements.in
requirements.txt

* Update dependencies
* boto3: 1.26.125 -> 1.26.138
* botocore: 1.26.138 -> 1.29.138
* sentry-sdk: 1.19.1 -> 1.24.0
* bandit: 1.7.4 -> 1.7.5
* ruff: 0.0.264 -> 0.0.269
* werkzeug: 2.3.3 -> 2.3.4
* Recompile requirements.txt
* Bump requests from 2.29.0 to 2.31.0 (from PR #923)
* Bump gitpython from 3.1.27 to 3.1.30 (from PR #909)

Updates 20230523

---

testlib/mini_poster.py

This fixes mini_poster use in my dev scripts where it wasn't seeing v1/
correctly in directory trees.

bug 1849352: fix mini_poster to identify v1 correctly

---

bin/send_crash_report.sh

Since the script uses `set -u`, undefined variables are an error, so the default value for `$1` doesn't work. If no command-line argument is provided, the script errors out immediately. This change makes the default value work as expected.

Fix script to send example crash report.

---

antenna/throttler.py
tests/unittest/test_throttler.py

This adds a map of product -> supported `Android_PackageName` values and a throttler rule to reject incoming crash reports where the configuration denotes a list of supported packagenames and either the `Android_PackageName` is missing or it's not in the supported list.
The initial set of supported packagenames is provided in bug-1819628.

bug-1819628: reject incoming crash reports by Android_PackageName

---

docker-compose.yml
systemtest/conftest.py

parameterize the fixture and skip when the param doesn't match the configured backend, showing the tested backend as part of the test name

bug-1882199: Verify that systemtests are using the intended backend

---

antenna/breakpad_resource.py
tests/unittest/test_breakpad_resource.py
tests/unittest/test_fs_crashstorage.py
tests/unittest/test_gcs_crashstorage.py
tests/unittest/test_s3_crashstorage.py

Because:
* Crash reporters specify a user-agent HTTP header in the HTTP POST request when submitting crash reports.
* The Firefox crash reporter was just updated to use a Rust re-write implementation, and we'd like to know which reports are submitted by this new crash reporter.
* The new crash reporter has a unique user-agent per https://bugzilla.mozilla.org/show_bug.cgi?id=1888071#c7.
This commit:
* Captures the user-agent in crash report metadata.

bug-1888201: capture user-agent and put it in metadata

---

antenna/ext/gcs/crashstorage.py
tests/unittest/test_gcs_crashstorage.py

when deploying antenna in stage, i found it was crashing when `app.verify()` was called, and tracked that to not having get bucket permissions.
We could grant get bucket permissions, but it seems unnecessary when we could only use the permissions we need.

bug-1881575: only require objectUser permissions for GCS

---

antenna/health_resource.py
bin/run_tests.sh
systemtest/test_dockerflow.py
tests/unittest/test_health_resource.py

This adds a "cloud" key to `/__version__` output so we can easily determine which cloud the service is running in.
To test:
1. run collector
2. check `http://localhost:8000/__version__` and make sure "cloud" value matches the cloud configuration you're using

bug-1887640: add "cloud" to `/__version__` output

---

antenna/__init__.py
antenna/app.py
antenna/breakpad_resource.py
antenna/crashmover.py
antenna/health_resource.py
antenna/libmarkus.py
bin/run_tests.sh
tests/unittest/conftest.py
tests/unittest/test_sentry.py

- **bug-1898341: remove statsd_namespace**
- **bug-1898341: capture metrics used in tests**
- **bug-1898341: switch to a single METRICS client**
- **bug-1898341: change HOST_ID to HOSTNAME and add host tag**
This does some minor cleanup. We don't use statsd_namespace so there's no point it having a configuration variable for it. This removes some header material from `antenna/__init__.py`.
This adds a markus backend to capture what metrics were emitted during tests. We can compare before-and-after after making fundamental changes like this to how metrics are emitted.
After I landed the `CaptureMetricsUsed` code, I captured the metrics, ran them through `sort` and `uniq` and get this:
```
histogram	breakpad_resource.crash_size	['payload:compressed']
histogram	breakpad_resource.crash_size …
```

bug-1898341: add host tag

---

bin/run_web.sh

to help investigate ongoing http 502 incident

Configure gunicorn to emit statsd metrics

---

antenna/app.py
docker/images/fakesentry/Dockerfile
requirements.in
requirements.txt
tests/test_sentry.py

This updates fillmore and kent to 2.0.0 which support the API changes in sentry-sdk >= 2.
kent 2.0.0 API changes: https://github.com/willkg/kent/releases/tag/v2.0.0
fillmore 2.0.0 API changes: https://github.com/willkg/fillmore/releases/tag/v2.0.0

Update sentry-sdk to 2.6.0, fillmore to 2.0.0, and kent to 2.0.0

---

.github/workflows/build-and-push.yml
.gitignore
docker-compose.override.yml
docker-compose.yml

by defining volume mounts in `docker-compose.override.yml` they are used by default in the dev environment, but can be disabled for CI by setting `COMPOSE_FILE`. This reduces the differences between dev and CI, which allows CI to take advantage of commands like `make setup` and `systemtest/test_env.sh local`.
This makes `docker-compose.override.yml` no longer ignored by git, which may be undesirable. If that's not acceptable, we could use the services with volume mounts in CI, because github actions support that (unlike circleci). That would require specifying `--user="$(id --user):$(id --group)"` in CI for `docker compose run` commands that touch /app to avoid permissions issues (note: I also tested this solution, it works).

Don't use custom docker compose services for CI

---

.github/workflows/build-and-push.yml
Makefile
docker-compose.yml
docker/images/nginx/Dockerfile
docker/images/nginx/client_body_timeout.conf.template
docker/images/nginx/nginx.conf
docker/images/nginx/upstream.conf.template
systemtest/test_env.sh

this enables running system tests for nginx in dev and CI.
for now, this does not publish the container for deployment in GKE.

bug-1894955: add nginx container to dev and ci environments

---

docker-compose.override.yml

This fixes the web container so that it mounts the repo directory as `/app` which allows us to see code changes without having to rebuild.
I think what's going on is that the override for `base` doesn't get pulled into the services that extend `base`.

Fix web container to mount volume in local dev environment

---

.editorconfig
antenna/app.py
antenna/crashmover.py
antenna/health_resource.py
antenna/liblogging.py
antenna/libmarkus.py
antenna/statsd_metrics.yaml
bin/run_lint.sh
docs/conf.py
docs/exts/__init__.py
docs/exts/document_metrics.py
docs/index.rst
docs/overview.rst
requirements.in
requirements.txt
tests/conftest.py
tests/test_breakpad_resource.py
tests/test_health_resource.py
tests/test_sentry.py

This upgrades Markus to 5.0.0 and documents the metrics. It also does some metrics-related cleanup by removing some things we weren't using.
~Note: The first commit is covered in pull #1051. I needed that in order to test changes. We should land that PR first and then rebase this one on top of that one.~

bug-1906108: upgrade markus to 5.0.0 and document metrics

---

antenna/throttler.py
tests/test_throttler.py

See this [comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1916751#c2) in the ticket for an estimate of the expected increase in crash volume as a result of this change.

bug-1916751: don't throttle background process crashes

---

docker-compose.yml

The devcontainer and pubsub container don't respond to the SIGTERM signal sent by Docker Compose by default. To speed up container shutdown, we configure signals that actually do to be sent in the first attempt.
(Antenna did not use tini, so I didn't need to remove it.)
https://mozilla-hub.atlassian.net/browse/OBS-361

OBS-361: Configure stop signals for Docker containers.

---

.github/dependabot.yml
docker/Dockerfile
docs/dev.rst

https://mozilla-hub.atlassian.net/browse/OBS-375

Prevent dependabot from proposing Python version upgrades beyond 3.11.

---

docker/config/local_dev.env

Previously, we used `STATSD_NAMESPACE` and set it in the local dev environment. We don't want to do that anymore since the application now emits full metrics keys. This removes the fake `STATSD_NAMESPACE` value from the local dev environment.
This mirrors https://github.com/mozilla-services/tecken/pull/3132 .

obs-541: remove statsd namespace in local dev environment

---

.devcontainer/Dockerfile
docker/Dockerfile
requirements.in

Use an earlier version of pip becuase of https://github.com/jazzband/pip-tools/issues/2176.

bug-1964356: Restrict pip to a version earlier than 25.1.
