mozilla-services/antenna

.travis.yml
bin/travis/test_dispatch.sh
requirements-dev.txt

Reworks travis scaffolding so it runs with sudo and runs a lint pass as
well as a tests pass.
Once more ... with meaning.

Add lint step to travis

---

circle.yml

Test commit, don't merge yet ;)

Don't deploy for dev branches, PRs, etc.

---

antenna/app.py

AppConfig lets us define application-scoped configuration that's global
to the whole project. We can pass bits of that as appropriate to
components that need it.
In this way, we can have good auto-generated documentation and less
tangling between components and the application.

Implement AppConfig

---

requirements.txt
tests/unittest/conftest.py
tests/unittest/test_fs_crashstorage.py

This updates Everett and then cleans up some of the test code to take
advantage of new features.

Update Everett to v0.3

---

antenna/app.py
tests/unittest/test_app.py

Add `/__lbheartbeat__` and `/__heartbeat__` endpoints.

Healthchecks

---

antenna/app.py
tests/unittest/test_fs_crashstorage.py

The crashstore component should be namespaced to ease configuration
confusion.

Fix crashstore namespace

---

Makefile
README.rst
docker-compose.yml
prod.env

This changes "make run" to kick off a prod-like environment rather
than a barebones one.
This also updates the README so it's helpful again.

Switch around hacking environment

---

antenna/loggingmock.py

I thought the way it was adding/removing handlers was ok, but then I hit
problems. I suspect I'm hitting propagation and possibly some ordering
issues or something.
Anyhow, this takes a more drastic approach to mocking and works more
reliably.

Fix logging mock

---

antenna/app.py
tests/unittest/conftest.py
tests/unittest/test_app.py
tests/unittest/test_crashstorage.py
tests/unittest/test_fs_crashstorage.py
tests/unittest/test_s3_crashstorage.py

* remove some unused things
* clean up some comments
* reduce vertical space usage

Minor cosmetic code cleanup

---

antenna/app.py
requirements.txt
tests/unittest/conftest.py
tests/unittest/test_crashstorage.py

This adds sentry support to Antenna. It also adds a
WSGILoggingMiddleware which is better for local development.

Bug #1316431: Add sentry

---

tests/systemtest/test_content_length.py
tests/systemtest/test_post_crash.py

@milescrabill Do these look ok?

System test fixes

---

Dockerfile

Move Dockerfile gunicorn config to env vars

---

tests/systemtest/test_20mblimit.py

We want to make sure that nginx is rejecting large payloads based on the actual
size of the payload and not the content-length.
Note: I can't test this locally at the moment because we're not using nginx in local development environments. So I'm going to land this and then "test" it when the systemtest runs for -dev.

Add test with large payload and wrong content-length

---

Dockerfile
requirements-newrelic.txt

pip install newrelic in the Dockerfile

---

antenna/app.py

Currently, if Antenna is sad or despondent at startup, we are blissfully
unaware. That turns out to be problematic. We want to know if our little Antenna
is having problems getting out of bed in the morning.
This fixes the startup code to send startup errors to Sentry.

Bug 1342583: Capture startup errors in sentry

---

circle.yml

This will help correlate builds across our many building things
@willkg r?

ci: also deploy antenna container to dockerhub with circle build num

---

antenna/breakpad_resource.py

Previously, a crashmover coroutine would spawn after an on_post. However, for
hand-wavey reasons, maybe a coroutine could "die" and if there's not an on_post
right afterwards, another one won't get spawned and Antenna might sit around for
a bit and not save something.
Anyhow, this adjusts things so that the heartbeat also kicks off coroutines if
appropriate.

Adjust crashmover spawning

---

antenna/ext/s3/connection.py

This adjusts the retry times for s3 connections increasing them to a base of 5
and also adding some jitter. The hope is that these improve the Antenna startup
situation where we have a hard time getting credentials (the current theory).

Bug 1347185: Adjust retry times for s3 connections

---

antenna/breakpad_resource.py

This fixes the has_work_to_do function so that it includes the outstanding
workers, too.

Bug 1337506: Include workers with work to do

---

bin/create_s3_bucket.py
bin/run_web.sh

This fixes the script a bit so that it's more informative in what it's doing.
Further, this adjusts run_web.sh so that it runs the script creating the bucket
if necessary. This reduces a bunch of first-time developer pain.

Fix create_s3_bucket.py script and add it to run_web.sh

---

tests/systemtest/test_content_length.py

If nginx exceeds the timeout when waiting for the rest of the request, it'll
just drop the connection. If the systemtest is connecting to the ELB, the ELB
turns that into an HTTP 504. If the systemtest is connecting directly to nginx,
then nginx just drops the connection and the systemtest fails.
This fixes the systemtest for the nginx case.

Fix the issue where nginx just drops the connection

---

Makefile
docs/_templates/layout.html
docs/conf.py
docs/index.rst
requirements.txt

* add index to the sidebar
* change the theme

Fix some issues with Sphinx

---

antenna/breakpad_resource.py
antenna/ext/crashstorage_base.py
antenna/ext/fs/crashstorage.py
antenna/ext/s3/crashstorage.py
antenna/throttler.py
antenna/util.py

I had done a bunch of args already. This fixes the remaining ones.
Fixes #75.

Add arg types to args in docstrings

---

antenna/app.py
tests/unittest/test_app.py

This makes the home page less weird.

Bug 1356368: Fix home page

---

README.rst
docker-compose.yml

Grafana has better graphing, so this will make local development easier.
This also adds some bits to the README for setting it up. When doing that, I
broke up the running section into smaller parts.

Switch from a statsd/graphite to a statsd/graphite/grafana container

---

antenna/throttler.py
tests/systemtest/conftest.py

This fixes something dumb I committed in the previous PR because I got side-tracked and didn't double-check my work. :(

1356319 test fix

---

docs/index.rst
docs/quickstart.rst

This makes it easier to get to the TOC on the index page.

Move quickstart to separate chapter

---

docs/spec_v1.rst

Found another blurb in my notes that should be in the spec. Pretty sure this is everything now.

Further clarify the "why didn't we go the edge route" text

---

circle.yml

ci: no more circle build # tagged docker pushes

---

.pyup.yml

refs: https://github.com/mozilla-services/github-management/issues/8#issuecomment-301470598
I'm not sure this will actually reduce the noise since I get the same output testing against my fork whether update all or none is set:
```
» pyup --log=INFO --repo=g-k/antenna --branch=pypup-update-all --user-token=<>
INFO:pyup.providers.github:Getting file at /.pyup.yml for branch pypup-update-all
got repo config: {'search': False, 'update': 'all', 'schedule': 'every day'}
INFO:pyup.bot:Runtime config is: {'search': False, 'requirements': [], 'branch': u'pypup-update-all', 'pin': True, 'schedule': 'every day', 'update': 'all', 'update_hashes': True, 'assignees': [], 'branch_prefix': u'pyup-', 'close_prs': True, 'label_prs': False, 'pr_prefix': u''}
Updating ...: 0it [00:00, ?it/s]
~/antenna - …
```

pyup update insecure

---

bin/ci/deploy-dockerhub.sh

circleci conf: only do things if DOCKER_DEPLOY=true

---

Dockerfile
requirements-newrelic.txt

We never really used New Relic for Antenna, so this removes the bits
that were left over from that.

fix bug 1444939 - nix new relic

---

.circleci/config.yml

and minor refactors to circleci

push docker images tagged with code sha1

---

Makefile

This moves `.PHONY` markings to just before the relevant rule. This reduces
accidental missing `.PHONY` markings.
This also redoes default and help so that the default is to be helpful
rather than tell you to ask for help.

Update Makefile to be like Socorro's

---

antenna/breakpad_resource.py
antenna/util.py
tests/unittest/test_breakpad_resource.py
tests/unittest/test_util.py

This removes the de-nulling code from Antenna. It'll now be done in the
processor.

fix bug 1357246: remove de-nulling code

---

antenna/app.py
antenna/ext/s3/connection.py
antenna/ext/s3/crashstorage.py
antenna/heartbeat.py
bin/create_s3_bucket.py
tests/unittest/test_s3_crashstorage.py

Parts of Antenna verify that they're configured correctly at instantiation time. This changes that so that everything gets instantiated and then everything that needs to verify something gets a chance to verify. This makes Antenna startup issues easier to debug.

fix bug 1529026: make verification a separate step

---

antenna/app.py
antenna/breakpad_resource.py
antenna/ext/crashstorage_base.py
antenna/ext/fs/crashstorage.py
antenna/ext/s3/connection.py
antenna/ext/s3/crashstorage.py
antenna/gunicornhooks.py
antenna/health_resource.py
antenna/metrics.py
antenna/sentry.py
antenna/throttler.py
antenna/util.py
setup.cfg

This fixes issues raised by flake8-docstrings which uses pydocstyle. I
didn't add it to the "make lint" pass because I'm on the fence about whether
to enforce it for everyone. However, it did make sense to run it once
and fix any issues and thus improve the docs.

Fix pydocstyle lint issues

---

antenna/breakpad_resource.py

The HTTP POST payload for a crash report is complete and has all the
information we need in it. Because of this, we should ignore the querystring
parameters which FieldStorage emits as items with no content type.

bug 1560168: ignore querystring params in HTTP POSTs

---

setup.cfg

This configures flake8 to match black.

Fix line length to 88

---

bin/release.py
setup.cfg

This allows us to create bugs with:
```
$ ./bin/release.py make-bug
```
and make tags with:
```
$ ./bin/release.py make-tag --with-bug=BUGID
```

Update release.py and codify configuration

---

antenna/util.py
requirements/default.txt
tests/unittest/test_util.py

This cleans up the readability of the retry code.
I wanted to do a cleanup pass before copying this code into Socorro to use there. I need it there to help clean up the boto crash storage.

Cleanup retry code

---

docker/run_tests_in_docker.sh

We just updated the Python docker container. This updates the test data container to be the same.

Update test data container

---

antenna/throttler.py
tests/unittest/test_throttler.py

This reject all incoming crash reports where the build id indicates it's over 2 years old. We don't have symbols for builds this old, so these crash reports aren't actionable.

bug 1513020: reject incoming crash reports with build id > 2 years

---

antenna/breakpad_resource.py

This lets us see how long decompression takes.

bug 1680036: add timer for decompression step

---

antenna/app.py
systemtest/conftest.py
systemtest/test_dockerflow.py

This fixes a test for the localdevenv so that it's using the right config thing.
This also adds some dockerflow tests to the systemtests.

bug 1723964: fix localdevenv test and add dockerflow tests

---

docs/architecture.rst
docs/configuration.rst
docs/deploy.rst
requirements.in
requirements.txt

This updates Everett to 3.0.0 and redoes the configuration documentation
using Everett's Sphinx directives.

Update Everett to 3.0.0

---

antenna/breakpad_resource.py
testlib/mini_poster.py
tests/unittest/test_breakpad_resource.py

This allows the payload to be either multipart/form-data or
multipart/mixed.

bug 1747398: add support for multipart/mixed

---

antenna/breakpad_resource.py
tests/unittest/test_breakpad_resource.py

For this project, we want maximum body part count.
The default of 64 hampers crash reports with more than 64 annotations
which happens.

bug 1562641: set max_body_part_count to infinity

---

antenna/breakpad_resource.py

We're seeing a lot of content types that don't jive with our crash
report payload specification. It's hard to tell where they're coming
from. For now, we're going to make the code more permissive and later
we'll build some better observability so we can track down issues.

bug 1757786: adjust the payload handling to be more permissive

---

bin/release.py

```
ae2b6c4 Add bug checking
d5d4946 Update black dev requirement
25c0900 Default Priority to P2 (#18)
16d1a9a Add tag summary line (#19)
```

Update release.py to latest version

---

antenna/breakpad_resource.py
tests/unittest/test_breakpad_resource.py

This changes some extraction issues to warnings and adds them as notes to the raw crash matadata collector notes.
* when the wrong content-type (or no content-type for dumps) is specified
* when annotation values aren't valid utf-8
* when "extra" is specified and there are also other annotations

bug 1760814: change some extract issues to warnings and add as notes

---

antenna/throttler.py
tests/unittest/test_throttler.py

This adds a throttler rule to accept only 25% of Firefox, ESR, Windows <= 8.1 crash reports.

bug 1849352: add throttler rule for Firefox ESR Windows <= 8.1

---

bin/circleci_push.sh

The upload script currently errors out for builds that are neither on the main branch nor for a git tag, since the CIRCLE_TAG variable will be undefined in these cases, and we use `set -u` to tell bash to error out on undefined variables. The script also errors out when DOCKERHUB_REPO is not set. This change makes the script more robust against undefined variables by checking every variable before it is used and returning with a success error code when no image upload is required.
I didn't test this locally, since I figured it will be tested automatically when CI runs.

bug 1859776: prevent Docker Hub upload script from crashing for non-main branch builds.

---

bin/license-check.py
bin/release.py
bin/service-status.py
pyproject.toml

This picks up:
* fix bug links in bugzilla bug description (willkg/socorro-release#38)
* make release.py work with https protocol (willkg/socorro-release#40)
* add `bin/service-status.py` and configuration

Update release.py and add service-status.py

---

.gitignore
docker-compose.yml

see also https://github.com/mozilla-services/eliot/pull/113 and https://github.com/mozilla-services/tecken/pull/2858

bug-1884408: Make ports exposed in docker compose configurable

---

antenna/ext/gcs/crashstorage.py
docs/overview.rst
systemtest/conftest.py
tests/unittest/test_gcs_crashstorage.py

and update overview doc to mention gcs

bug-1881575: restore legacy path behavior for gcs

---

docker/Dockerfile

See #mozilla-services/socorro-stackwalk/pull/15

specify platform in base image

---

.circleci/config.yml
pyproject.toml

I'll update Jenkins after landing this.

bug-1882879: update tag scheme to vYYYY.MM.DD[-N]

---

docker-compose.yml
docker/images/grafana/Dockerfile
docker/images/pubsub-emulator/Dockerfile

by putting external images in dockerfiles

Work around dependabot not updating docker-compose

---

.github/workflows/manual-deployment.yml

The workflow was copied without any changes from Tecken and Eliot.
https://mozilla-hub.atlassian.net/browse/OBS-467

OBS-467: Add workflow to manually trigger a deployment.
